pipeline {
    agent any
    //stage of test
    stages {
      stage('Test') {
          environment {
                Tester = "${params.Tester}"
            }
            steps {
                echo "test passed by $Tester!"
            }
        }
    }
}