pipeline {
    agent any
  //paramters
parameters {
        //string parameter
        string(name: 'Greeting', defaultValue: 'Hello', description: 'How should I greet the world?')
        //choice paramter
        choice(name: 'Stage', choices: ['dev', 'test', 'uat'], description: 'Deployment Stage')
        //choice(name: 'Tester', choices: ['Danny', 'Ruby', 'William'], description: 'Tester')
    }
    //stages of build
    stages {
      stage('Init') {
            steps {
                echo "${params.Greeting} World!"
            }
        }
        stage('Build') {
            environment {
                Greet = "${params.Greeting}"
                Tester = "${params.Tester}"
            }
            steps {
                /*
                The Groovy script you provided is formatting the first line 
                as a blank line in the resultant script. The shebang, telling
                the script to run with /bin/bash instead of /bin/sh, needs 
                to be on the first line of the file or it will be ignored.
                */
                echo "The test is running in ${params.Stage} mode" //paramas seems only can be used outside sh
                sh '''#!/bin/bash
                echo "Test parameter $Greet"
                bash hw.sh
                exit
                '''
            }
        }
        /*post build action, build another project named MyProject-Test'*/
        stage ('Starting downstream job ') {
            steps {
                build job: 'MyProject-Test'
             }
        }
    }
  /*
    post { 
        always { 
            echo 'I will always say Hello again!'
        } 
    }
    */
}