pipeline {
    agent any
  //paramters
parameters {
        //string parameter
        string(name: 'Greeting', defaultValue: 'Hello', description: 'How should I greet the world?')
        //choice paramter
        choice(name: 'Stage', choices: ['dev', 'test', 'uat'], description: 'Deployment Stage')
    }
    //stages of build
    stages {
      stage('Init') {
            steps {
                echo "${params.Greeting} World!"
            }
        }
        stage('Build') {
            steps {
                /*
                The Groovy script you provided is formatting the first line 
                as a blank line in the resultant script. The shebang, telling
                the script to run with /bin/bash instead of /bin/sh, needs 
                to be on the first line of the file or it will be ignored.
                */
                sh '''#!/bin/bash
                echo "The test is running in ${params.Stage} mode"
                ls
                bash hw.sh
                exit
                '''
            }
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
        }
    }
}